### PR TITLE
INFORMATION_SCHEMA uppercasing

### PR DESCRIPTION
**Pull request by mjsqu**
Change required for databases with case sensitive collation

### CODE REVIEW

**Comment by mjsqu** [comment]
## Testing

### master branch

This is the original code before this PR:

##### Verifying remote is s7clarke10
```bash
~/pipelinewise-tap-mssql$ git remote -v
origin  https://github.com/s7clarke10/pipelinewise-tap-mssql.git (fetch)
origin  https://github.com/s7clarke10/pipelinewise-tap-mssql.git (push)
```

##### Checking out master
```bash
~/pipelinewise-tap-mssql$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.1
```

##### Installing tap
```bash
~/pipelinewise-tap-mssql$ pip install .
Processing /home/meltano/pipelinewise-tap-mssql
Requirement already satisfied: attrs==16.3.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (16.3.0)
Requirement already satisfied: backoff==1.8.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (1.8.0)
Requirement already satisfied: pendulum>=1.2.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (2.1.2)
Requirement already satisfied: pymssql>=2.2.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (2.2.7)
Requirement already satisfied: singer-python==5.9.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (5.9.0)
Requirement already satisfied: ciso8601 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.3.0)
Requirement already satisfied: jsonschema==2.6.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.6.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.8.2)
Requirement already satisfied: pytz==2018.4 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2018.4)
Requirement already satisfied: simplejson==3.11.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (3.11.1)
Requirement already satisfied: pytzdata>=2020.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from pendulum>=1.2.0->tap-mssql==1.0.5) (2020.1)
Requirement already satisfied: six>=1.5 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from python-dateutil>=2.6.0->singer-python==5.9.0->tap-mssql==1.0.5) (1.16.0)
Using legacy 'setup.py install' for tap-mssql, since package 'wheel' is not installed.
Installing collected packages: tap-mssql
  Attempting uninstall: tap-mssql
    Found existing installation: tap-mssql 1.0.5
    Uninstalling tap-mssql-1.0.5:
      Successfully uninstalled tap-mssql-1.0.5
    Running setup.py install for tap-mssql ... done
Successfully installed tap-mssql-1.0.5
```

##### Running discover

The discovery fails due to the case sensitivity of the database. The system view `information_schema.tables` cannot be found:

```bash
~/pipelinewise-tap-mssql$ tap-mssql -c config.json --discover > catalog.json
INFO Server Parameters: version: Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)
        Apr  1 2023 12:10:46
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)
, lock_timeout: -1,
INFO Preparing Catalog
INFO Fetching tables
CRITICAL (208, b"Invalid object name 'information_schema.tables'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (208, b"Invalid object name 'information_schema.tables'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meltano/.venv/ms/bin/tap-mssql", line 11, in <module>
    load_entry_point('tap-mssql==1.0.5', 'console_scripts', 'tap-mssql')()
  File "/home/meltano/.venv/ms/lib/python3.9/site-packages/tap_mssql/__init__.py", line 766, in main
    raise exc
  File "/home/meltano/.venv/ms/lib/python3.9/site-packages/tap_mssql/__init__.py", line 763, in main
    main_impl()
  File "/home/meltano/.venv/ms/lib/python3.9/site-packages/tap_mssql/__init__.py", line 749, in main_impl
    do_discover(mssql_conn, args.config)
  File "/home/meltano/.venv/ms/lib/python3.9/site-packages/tap_mssql/__init__.py", line 310, in do_discover
    discover_catalog(mssql_conn, config).dump()
  File "/home/meltano/.venv/ms/lib/python3.9/site-packages/tap_mssql/__init__.py", line 213, in discover_catalog
    cur.execute(
  File "src/pymssql/_pymssql.pyx", line 476, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.ProgrammingError: (208, b"Invalid object name 'information_schema.tables'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
```

**Comment by mjsqu** [comment]
### correct_case_for_CS_collation branch

##### Associate new local branch with this PR
```bash
~/pipelinewise-tap-mssql$ git fetch origin pull/11/head:fix/correct_case_for_CS_collation
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 32 (delta 14), reused 9 (delta 5), pack-reused 0
Unpacking objects: 100% (32/32), 23.44 KiB | 2.13 MiB/s, done.
From https://github.com/s7clarke10/pipelinewise-tap-mssql
 * [new ref]         refs/pull/11/head -> fix/correct_case_for_CS_collation
```

##### Checkout the branch
```bash
~/pipelinewise-tap-mssql$ git checkout fix/correct_case_for_CS_collation
Switched to branch 'fix/correct_case_for_CS_collation'
```

##### Install tap
```bash
~/pipelinewise-tap-mssql$ pip install .
Processing /home/meltano/pipelinewise-tap-mssql
Requirement already satisfied: attrs==16.3.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (16.3.0)
Requirement already satisfied: backoff==1.8.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (1.8.0)
Requirement already satisfied: pendulum>=1.2.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (2.1.2)
Requirement already satisfied: pymssql>=2.2.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (2.2.7)
Requirement already satisfied: singer-python==5.9.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from tap-mssql==1.0.5) (5.9.0)
Requirement already satisfied: ciso8601 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.3.0)
Requirement already satisfied: jsonschema==2.6.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.6.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2.8.2)
Requirement already satisfied: pytz==2018.4 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (2018.4)
Requirement already satisfied: simplejson==3.11.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from singer-python==5.9.0->tap-mssql==1.0.5) (3.11.1)
Requirement already satisfied: pytzdata>=2020.1 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from pendulum>=1.2.0->tap-mssql==1.0.5) (2020.1)
Requirement already satisfied: six>=1.5 in /home/meltano/.venv/ms/lib/python3.9/site-packages (from python-dateutil>=2.6.0->singer-python==5.9.0->tap-mssql==1.0.5) (1.16.0)
Using legacy 'setup.py install' for tap-mssql, since package 'wheel' is not installed.
Installing collected packages: tap-mssql
  Attempting uninstall: tap-mssql
    Found existing installation: tap-mssql 1.0.5
    Uninstalling tap-mssql-1.0.5:
      Successfully uninstalled tap-mssql-1.0.5
    Running setup.py install for tap-mssql ... done
Successfully installed tap-mssql-1.0.5
```

##### Run discovery
```bash
~/pipelinewise-tap-mssql$ tap-mssql -c config.json --discover > catalog.json
INFO Server Parameters: version: Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)
        Apr  1 2023 12:10:46
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)
, lock_timeout: -1,
INFO Preparing Catalog
INFO Fetching tables
INFO Tables fetched, fetching columns
INFO ARRAYSIZE=1
INFO Columns Fetched
INFO Catalog ready
```


##### Check a few lines from the catalog
```bash
~/pipelinewise-tap-mssql$ head -10 catalog.json
{
  "streams": [
    {
      "tap_stream_id": "cdc-lsn_time_mapping",
      "table_name": "lsn_time_mapping",
      "schema": {
        "properties": {
          "start_lsn": {
            "inclusion": "unsupported",
            "description": "Unsupported column type"
~/pipelinewise-tap-mssql$ tail -10 catalog.json
          ],
          "metadata": {
            "selected-by-default": true,
            "sql-datatype": "datetime"
          }
        }
      ]
    }
  ]
}
~/pipelinewise-tap-mssql$ grep tap_stream_id catalog.json
      "tap_stream_id": "cdc-lsn_time_mapping",
      "tap_stream_id": "dbo-mpi_audhead"
...
~/pipelinewise-tap-mssql$ grep datatype catalog.json
            "sql-datatype": "binary"
            "sql-datatype": "datetime"
            "sql-datatype": "datetime"
            "sql-datatype": "varbinary"
            "sql-datatype": "binary"
            "sql-datatype": "bigint"
            "sql-datatype": "smallint"
            "sql-datatype": "int"
            "sql-datatype": "smallint"
            "sql-datatype": "datetime"
            "sql-datatype": "datetime"
...
```

**Comment by mjsqu** [comment]
I was also subsequently able to produce valid `RECORD` messages by adding:

```json
"selected": true,
"replication-method": "FULL_TABLE"
```
to a stream definition in the produced catalog. I also performed a successful run with replication-method set to "LOG_BASED"

**Comment by mjsqu** [comment]
INFORMATION_SCHEMA view names have been uppercased also, as they are also required to be uppercase in databases with case sensitive collation.

**Comment by s7clarke10** [comment]
Thank you for this change @mjsqu . After discussions and looking at other opinions https://stackoverflow.com/questions/52898/what-is-the-use-of-the-square-brackets-in-sql-statements on the topic of using square brackets or just uppercase Schema.Table naming we have settled on uppercase only. This change resolves a real issue if the INFORMATION_SCHEMA is in upper case.

Approved.

**Pull request merged**
